adapter/adapter.h
adapter/ancs/ancs.c
adapter/cmd/cmd.c
adapter/printf/printf.c
ancs_client.c
ancs_service_data.c
ancs_service_data.h
common/common.h
driver/uart/uart.c
foxter601.xip
serial_service.c
user_config.h

1. cmd parse and struct api
2. ancs message api
3. printf api

Mlw 0422 cmd

---

adapter/adapter.c
adapter/adapter.h
adapter/clock/clock.c
adapter/cmd/cmd.c
adapter/mag/mag.c
adapter/nvm/nvm.c
adapter/printf/printf.c
adapter/step/step.c
common/common.h
driver/magnetometer/magnetometer.c
foxter601.xip

1.ancs_get()
2.cmd_get()
3.step_get()
4.angle_get()

Mlw 0430 sensor

---

adapter/adapter.h
adapter/ble/ble.c
adapter/button/button.c
ancs_client.c
driver/uart/uart.c
foxter601.xip

1. add ble switch
2. add uart block mode(115200 bitrate, no internal delay)

Mlw 0505 ble

---

adapter/adapter.c
adapter/adapter.h
adapter/cmd/cmd.c
adapter/nvm/nvm.c
adapter/step/step.c
ancs_client.c
ancs_csr101x_A05.keyr
app_gatt.h
business/business.c
business/state/state.h
business/state/state_clock.c
business/state/state_notify.c
business/state/state_nvm_access.c
common/common.h
foxter601.xip
user_config.h

1. add cmd response（add state_nvm_access.c）
2. update nvm storage model
3.  set slotA to 4300, nvm size to 100, sotre length to 82
4. update android msg test cmd

Mlw 0624 nvm resp

---

gap_service.c
user_config.h

fixed app pair to dev problem, finally!

Mlw 0719 pair

---

adapter/adapter.c
adapter/adapter.h
ancs_csr101x_A05.keyr
business/state/state_ble_switch.c
business/state/state_cmd_set_time.c

1. fixed pair code format error problem
2. removed some no use code

Mlw 0719 paircode

---

adapter/adapter.c
adapter/adapter.h
adapter/ancs/ancs.c
adapter/battery/bat.c
adapter/clock/clock.c
adapter/cmd/cmd.c
adapter/motor/motor_manage.c
adapter/nvm/nvm.c
adapter/step/step.c
ancs_client.c
business/business.c
business/state/state.h
business/state/state_battery_week_switch.c
business/state/state_ble_switch.c
business/state/state_clock.c
business/state/state_notify.c
business/state/state_run_test.c
business/state/state_time_adjust.c
business/state/state_zero_adjust.c
common/common.h
serial_service.c
user_config.h

1.添加实时计步发送到app
2.修复配对码无效问题
3.修复非连接情况下运动量指针不工作的问题
4.修复调零模式会导致手表重启的问题（需要压测）
5.修复退出调零模式部分指针不能归位的问题

rollback from 0808 to 0724

---

adapter/adapter.c
business/business.c
business/state/state_clock.c

1. add watch find phone
2. add sync steps when connected（not iOS）

add A button shot press to find phone; add steps sync to phone when connected

---

adapter/config.h
common/common.h

1.keya,keyb按键方向切换
2.星期显示从星期1开始

week:monday sunday modify and keya keyb change

---

adapter/adapter.h
adapter/ancs/ancs.c
adapter/ble/ble.c
adapter/cmd/cmd.c
business/business.c
business/state/state_ble_switch.c
business/state/state_clock.c
business/state/state_notify.c
common/common.h
serial_service.c
user_config.h

1. fix ANCS paired problem
2. fix NOTIFY motor confused problem
3. add adv name with MAC
4. add KEY_M_SHORT_PRESS to clear received notify msg

Mlw 0822 notify

---

adapter/adapter.c
adapter/adapter.h
adapter/ble/ble.c
ancs_client.c
ancs_client.h
app_gatt.h
business/state/state_ble_switch.c
csr_ota_service.c
user_config.h

1.  fix reboot & switch off/on no notify problem

Mlw 0826 notify

---

adapter/adapter.c
adapter/adapter.h
adapter/clock/clock.c
adapter/vibrator/vib.c
common/common.h
driver/driver.c
driver/driver.h
driver/timer/timer.c
foxter601.xip

1.timer add delete handler;
2.vibrator init,but not complete

Renpf 0829 vibrator

---

adapter/clock/clock.c
adapter/cmd/cmd.c
adapter/vibrator/vib.c
business/business.c
business/state/state_clock.c
business/state/state_notify.c
user_config.h

1. add vibration control logic
2. fixed date-31 problem(not test)

Mlw 0905 vib

---

adapter/adapter.h
adapter/motor/motor_manage.c

1.add motor run status get api, just for get  and set motor cur pos

add motor status ptr get api

---

adapter/adapter.c
adapter/adapter.h
adapter/charge/charge_status.c
adapter/config.h
common/common.h
driver/charge/charge.c
driver/driver.c
driver/driver.h
foxter601.xip

add charge status

---

adapter/adapter.c
adapter/adapter.h
adapter/battery/bat.c
adapter/cmd/cmd.c
adapter/mag/mag.c
adapter/motor/motor_manage.c
adapter/nvm/nvm.c
adapter/step/step.c
adapter/vibrator/vib.c
ancs_client.c
business/business.c
business/state/state.h
business/state/state_battery_week_switch.c
business/state/state_ble_switch.c
business/state/state_charge.c
business/state/state_clock.c
common/common.h
foxter601.xip
serial_service.c
user_config.h

1. 修复OTA（重启）原点丢失的问题
2. 修复M键短按不能切换星期电量指针的问题
3. 添加蓝牙断开震动5下功能
4. 添加充电时电量指针在电量区域摆动功能

Mlw 0906 mag

---

adapter/config.h
common/common.h
driver/motor/motor_activity.c
driver/motor/motor_battery_week.c
driver/motor/motor_date.c
driver/motor/motor_hour.c
driver/motor/motor_item.c
driver/motor/motor_minute.c
driver/motor/motor_notify.c
foxter601.xip

motor optimise

---

adapter/battery/bat.c

battery level smooth

---

adapter/motor/motor_manage.c

optimize hour_minute work mode

---

adapter/adapter.c

charge motor run from cur power to 100%

---

log.c
user_config.h

1. fix time slow problem
2. fix week confuse problem

do not set week pointer right now

---

adapter/clock/clock.c

1.slove clock slow problem:when enter clock irq, start clock timer imediately
2.time sync from 1min to 1sec,then state will change within 1sec

solve clock slow problem && 1min to 1sec sync time

---

adapter/adapter.c
adapter/adapter.h
business/state/state.h
business/state/state_battery_week_switch.c
business/state/state_ble_switch.c
business/state/state_clock.c
log.c
user_config.h

1. add M long press disconnect to trig vibrate
2. fix week did not auto update problem
3. fix sometimes motor long vibrate problem(need to test)

Mlw 1111 optimize
